# Site settings
title: Work stuff from Reinier
email: rvanmaanen@xpirit.com
description: >-
  A blog about cool things I came across and stuff I had to Google myself, hope it helps someone else!
baseurl: ""
url: "https://r-vm.com"
twitter_username: maanenreinier
github_username:  rvanmaanen
linkedin_username: reiniervanmaanen
show_excerpts: false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag