# Site settings
title: Reinier's blog
email: rvanmaanen@xpirit.com
description: >-
  A blog about cool things I came across and stuff I had to Google myself, hope it helps someone else!
baseurl: ""
url: "http://rvanmaanen.github.io"
twitter_username: maanenreinier
github_username:  rvanmaanen

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
