# Site settings
title: Workbits from Reinier
email: rvanmaanen@xpirit.com
description: >-
  A blog about cool things I came across and stuff I had to Google myself, hope it helps someone else!
baseurl: ""
url: "https://r-vm.com"
twitter_username: maanenreinier
github_username:  rvanmaanen
linkedin_username: reiniervanmaanen
show_excerpts: false

# Google Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-121311213-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-seo-tag
  
