# Site settings
title: r-vm.com
email: rvanmaanen@xpirit.com
description: >-
  A blog about anything related to my work, probably mostly stuff I did or had to Google myself, hope it helps someone else!
baseurl: ""
url: "https://r-vm.com"
twitter_username: maanenreinier
github_username:  rvanmaanen
linkedin_username: reiniervanmaanen
show_excerpts: true
author: Reinier van Maanen

google_analytics: UA-121311213-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag